### ISSUE TITLE
Failed to open stream: No such file or directory in Drupal\Core\Asset\CssCollectionOptimizerLazy->generateHash

### ISSUE THREAD

**Issue by arttus** [NETNODEAG/nodehive-headless-cms-ce#3]
Just an FYI, getting this error on a fresh install with ddev on mac.

Error message
Warning: file_get_contents(modules/contrib/nodehive_core/modules/nodehive_visualeditor/css/gin-utility-classes.css): Failed to open stream: No such file or directory in Drupal\Core\Asset\CssCollectionOptimizerLazy->generateHash() (line 43 of core/lib/Drupal/Core/Asset/AssetGroupSetHashTrait.php).

Looks great for the most part, few other errors here and there, but it could be because there is no content. You might want to consider having a demo content recipe?

**Comment by arttus** [comment]
Also i haven't installed the front-end yet...

**Comment by lukasfischer** [comment]
@arttus fixed now. Please run composer update
